// Code generated by protoc-gen-go. DO NOT EDIT.
// source: beacon.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	beacon.proto
	client.proto
	envelope.proto
	epaxos.proto
	service.proto

It has these top-level messages:
	BeaconRequest
	BeaconReply
	ProposeRequest
	ProposeReply
	PeerRequest
	PeerReply
	PrepareRequest
	PrepareReply
	PreAcceptRequest
	PreAcceptReply
	AcceptRequest
	AcceptReply
	CommitRequest
	TryPreAcceptRequest
	TryPreAcceptReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BeaconRequest struct {
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *BeaconRequest) Reset()                    { *m = BeaconRequest{} }
func (m *BeaconRequest) String() string            { return proto.CompactTextString(m) }
func (*BeaconRequest) ProtoMessage()               {}
func (*BeaconRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BeaconRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type BeaconReply struct {
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *BeaconReply) Reset()                    { *m = BeaconReply{} }
func (m *BeaconReply) String() string            { return proto.CompactTextString(m) }
func (*BeaconReply) ProtoMessage()               {}
func (*BeaconReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BeaconReply) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func init() {
	proto.RegisterType((*BeaconRequest)(nil), "pb.BeaconRequest")
	proto.RegisterType((*BeaconReply)(nil), "pb.BeaconReply")
}

func init() { proto.RegisterFile("beacon.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 94 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x4a, 0x4d, 0x4c,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xd2, 0xe5, 0xe2,
	0x75, 0x02, 0x8b, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x70, 0x71, 0x96, 0x64,
	0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x04,
	0x94, 0xb4, 0xb9, 0xb8, 0x61, 0xca, 0x0b, 0x72, 0x2a, 0xf1, 0x2b, 0x4e, 0x62, 0x03, 0x5b, 0x63,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x5c, 0xfd, 0x18, 0x76, 0x00, 0x00, 0x00,
}
